name: Reusable Deploy Workflow
on: 
  workflow_call:
    inputs:
      artifact-name: 
        description: The name of the Deployable artifact
        required: false
        default: dist
        type: string
    outputs: 
      result:
        description: The Result Of the Deployment Operation
        value: ${{ jobs.deploy.outputs.outcome }}
jobs:
  deploy:
    outputs:
      outcome: ${{ steps.set-result.outputs.step-result }}
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: List Fiels Of Artifact
        run: ls 
      - name: output Info 
        run: echo "Deploying & Uploading..."
      - name: Set Result Output
        id: set-result
        run: echo "step-result=success" >> $GITHUB_OUTPUT
